# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fecf4bbab6178bd42dc20adeeb58d70570cdf5df31f371bd44621b8eec2819fa13d0d7f4197711f5e867f828bba4e697d8b4750805440d074f877388c6a12282

test:
  secret_key_base: 1ac25565a1f4431247e0d220a198b4d4eddff81644d509c6c15b7282c60ec12fdd6ef5133ac111c6af9fe2550116fe7dd860348d874102f20c6415b003b349a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
